export const localQuestions = [
  "What are your hobbies?",
  "Why do you like your hobbies so much?",
  "How often do you do these hobbies?",
  "How long have you been doing these hobbies, and how did you get started?",
  "What hobbies did you used to have, but now do not?",
  "Is it important to have hobbies? Why/why not?",
  "How much free time do you usually have?",
  "How important is time to you?",
  "If you had more free time, what would you do?",
  "'Time is money.' Do you agree or disagree? Why?",
  "How do you feel about time that is wasted?",
  "How much sleep do you usually get?",
  "Why do some people sleep well while other people do not sleep well?",
  "What do you do when you have trouble sleeping?",
  "What time do you usually go to sleep? What time do you usually get up?",
  "Have you ever slept in a strange place that was not a bed?",
  "What types of music do you like/dislike?",
  "How do certain kinds of music make you feel?",
  "What types of music come from your country?",
  "What’s your favorite song/album/artist?",
  "What music is popular in your country right now?",
  "What is your definition of risk?",
  "Are you a risk taker? Why/why not?",
  "What are the advantages/disadvantages of taking risks?",
  "What risks do you come across in your work/life?",
  "What risks have you taken in your life?",
  "How motivated are you in general?",
  "What motivates you to do things?",
  "What is the best motivator to succeed?",
  "What do you do when you feel demotivated?",
  "What is a good way to motivate others?",
  "What are your current goals in life?",
  "How do you plan to reach your goals?",
  "How often do you set goals for yourself?",
  "What goals have you set and achieved in the past?",
  "How do you feel when you reach your goals?",
  "How often do you go to restaurants?",
  "What is your favorite restaurant? Why?",
  "What do you usually order at a restaurant?",
  "What is the restaurant experience like in your country?",
  "Have you ever worked in a restaurant?",
  "If you owned a restaurant, what kinds of food would you serve?",
  "What is the most amazing thing about the brain?",
  "What is the most mysterious thing about the brain?",
  "What are some extraordinary things some people can do with their brains?",
  "Will we ever be able to augment our brain with technology? Would you?",
  "What do you wish your brain was better at?",
  "Do you think male and female brains are better at different tasks? Why or why not?",
  "What do you think about most?",
  "What does your brain do that you hate?",
  "Do you think humans will ever completely understand the brain? Why or why not?",
  "When do you use your brain the most?",
  "How important are books to you?",
  "What would life be like without books?",
  "What kinds of books do you like?",
  "Do you prefer paperbacks or hardbacks?",
  "If you wrote a book, what would you write about?",
  "If you could only have one book for the rest of your life, what would it be and why?",
  "Do you think the Internet will make books disappear",
  "What do you think of the idea of E-books?",
  "What book would you recommend for children?",
  "How many books have you read in English?",
  "What is the most beautiful country in the world?",
  "What things are necessary for a country to be a country?",
  "What country would you love to live in?",
  "What is the most dangerous country in the world?",
  "Would the world be better with more or fewer countries?",
  "Which country produces the most delicious food?",
  "Do you think news is usually happy or sad?",
  "How important is keeping up to date with the news to you?",
  "Do you prefer to watch, listen to or read about news?",
  "What areas of the world are you most interested in",
  "What was the last piece of good news you heard?",
  "What news story are you following at the moment?",
  "Do you trust everything you read, see or hear on the news?",
  "What is your usual morning routine?",
  "How are weekend mornings different from weekday mornings?",
  "Is morning the best time to study and get things done?",
  "Are you a morning person?",
  "What do you like doing in the morning?",
  "What are the mysteries of the world?",
  "How has your personality changed over the years?",
  "What of your personality traits do you like most?",
  "What are the personality differences between you and other family members?",
  "What is your favourite restaurant and why?",
  "What kind of restaurant would you like to open?",
  "Have you ever complained about the food or service in a restaurant?",
  "Would you like to work as a restaurant critic?",
  "Would you like to eat at a different restaurant every night for the rest of your life?",
  "Where do most accidents occur?",
  "What should the penalty be for someone who causes a car accident?",
  "How should schools teach kids about accidents?",
  "Agree or disagree?: Pizza is more delicious than chicken.",
  "Agree or disagree?:  English is easy to learn.",
  "Agree or disagree?:  Living in the city is better than living in the country.",
  "Agree or disagree?:  Dogs are the best pets.",
  "Agree or disagree?:  I love trying new foods.",
  "Agree or disagree?:  All students should go to university.",
  "Agree or disagree?:  My favorite thing to do on the weekend is sleep.",
  "Agree or disagree?:  Ten year olds should have smart phones.",
  "Agree or disagree?:  Coke is more refreshing than Sprite.",
  "Agree or disagree?:  All students should learn a musical instrument.",
  "Agree or disagree?:  I would be a good teacher.",
  "Agree or disagree?:  Teenagers should go to bed before 11pm.",
  "Agree or disagree?:  People should exercise every day.",
  "Agree or disagree?:  Men should work and women should stay home.",
  "Agree or disagree?:  Ice cream is the best summer snack.",
  "Agree or disagree?:  It is better to be smart than good-looking.",
  "Agree or disagree?:  My country is the best country in the world.",
  "Agree or disagree?:  All teenagers should volunteer.",
  "Agree or disagree?:  Getting good grades is more important than having fun.",
  "Agree or disagree?:  Breakfast is the most important meal of the day.",
  "Agree or disagree?:  McDonald’s is the best fast food restaurant.",
  "Agree or disagree?:  Basketball is the most fun sport to play.",
  "Agree or disagree?:  Learning about other cultures is important.",
  "Agree or disagree?:  It’s OK to miss a day of school.",
  "Agree or disagree?:  Dancing is easier than singing.",
  "Agree or disagree?:  Music and art are important subjects.",
  "Agree or disagree?:  Winter is better than summer.",
  "Agree or disagree?:  Italian food is the most delicious kind of food.",
  "Agree or disagree?:  Global warming is caused by humans.",
  "Agree or disagree?:  Saturday is the best day of the week.",
  "What do you like most about winter vacation?",
  "When do you usually wake up during winter vacation?",
  "What chores do you do during winter vacation?",
  "Why do schools have winter vacations?",
  "Have you ever traveled during winter vacation?",
  "Where do you want to travel?",
  "Are you happy or sad when vacation ends? Why?",
  "What do you like least about winter vacation?",
  "When do you usually go to bed during winter vacation?",
  "Do you wish winter vacation was longer or shorter? Why?",
  "Would you rather have a long winter vacation or several shorter vacations throughout the school year?",
  "What do you miss about school during winter vacation?",
  "Do you think adults should have winter vacation too? Why or why not?",
  "What is your daily routine during winter vacation?",
  "What fun activities do you do during winter vacation?",
  "How is winter vacation different than summer vacation?",
  "Do you visit school during winter vacation? Why?",
  "Do you have homework during winter vacation?",
  "Do you like to stay home during winter vacation or do you like to go out?",
  "What is something you can do during winter vacation that you can’t do during the regular school year?",
  "When you were young, what did you do during winter vacation?",
  "How old are you? When’s your birthday? Where were you born?",
  "What’s the best age to be?",
  "What are three bad things about being your current age?",
  "Do you think people should be forced to retire at 65? Why? Why not?",
  "Do you 'act your age?' Why? Why not?",
  "What’s the best age to get married?",
  "What are some good habits that slow down the ageing process?",
  "Would you take magic medicine to stop ageing?",
  "What does 'Age is just a number' mean?",
  "How old are you? When’s your birthday? Where were you born?",
  "Which time of your life was the most fun: elementary school, middle school, high school, or university",
  "What are three good things about being your current age",
  "Do you worry about getting older?",
  "Would you like to live forever?",
  "Do you 'look your age?' Why/Why not?",
  "What is the voting age in your country? Do you think this is fair?",
  "What are some bad habits that speed up the ageing process?",
  "What does 'Age is the price of wisdom' mean?",
  "What animal is the cutest?",
  "What animal did you like when you were younger?",
  "What is your favorite farm animal?",
  "Which animal exists in your country but is difficult to see?",
  "What is your favorite animal movie?",
  "What animal is the scariest?",
  "Which animal has a similar personality to you?",
  "Are pets family members? Why or why not?",
  "Which animal is the smartest?",
  "What animal can you see every day?",
  "Which animal would you like to have as a pet?",
  "What is your favorite cartoon animal?",
  "What is the most playful animal?",
  "Which family member likes animals the most?",
  "Do you think animals can understand human language? Why or why not?",
  "What is your favorite zoo animal?",
  "Which animal would you choose as a pet, a turtle or a rabbit?",
  "If you could be an animal for a day which animal would you be?",
  "Which animal makes the funniest sound?",
  "What stuffed animal did you have when you were young?",
  "How often are you sick?",
  "When you are sick, do you always go to the doctor?",
  "Can catching a cold be prevented?",
  "How often do you get a physical exam?",
  "Have you ever had to stay overnight in the hospital?",
  "What is your favorite “sick day” activity?",
  "Does cold medicine work?",
  "Besides medicine, what else can you buy at a pharmacy?",
  "When (season or month) do you usually get sick?",
  "Do you see the same doctor every time you’re sick? Why? Why not?",
  "When was the last time you were sick? What was wrong?",
  "When you are sick, do you stay home from school or work?",
  "What do you eat and drink when you are sick?",
  "Do you usually get an annual flu shot?",
  "What are some ways to prevent an illness from spreading?",
  "Why are children sick more often than adults?",
  "Which is more uncomfortable, a headache or a stomachache?",
  "Besides medicine, is there anything else that helps you feel better when you are sick?",
  "Would you rather be sick with a cough or a runny nose?",
  "Who is sick more often, you or your husband/wife?",
  "What is the best way to find a good job?",
  "What is the best way to become rich?",
  "What is the best way to spend the weekend?",
  "What is the best way to keep your body healthy?",
  "What is the best way to learn a musical instrument?",
  "What is the best way to learn to drive a car?",
  "What is the best way to become famous?",
  "What is the best way to be organized at home and at school?",
  "What is the best way to speak a new language fluently?",
  "What is the best way to save money?",
  "What is the best way to choose a new book at the library?",
  "What is the best way to meet new friends?",
  "What is the best way to prepare for a school presentation?",
  "What is the best way to quit a bad habit?",
  "What is the best way to be a good friend?",
  "What is the best way to keep your mind healthy?",
  "What is the best way to always be on time?",
  "What is the best way to celebrate your birthday?",
  "What is the best way to memorize 100 words?",
  "What is the best way to cook a delicious new recipe?",
  "What is body language?",
  "What’s a gesture? Give three examples.",
  "How do you ‘read’ another person’s body language? Why is it useful?",
  "Compare your country’s greetings with those of a foreign country.",
  "What form of body language do you use most often?",
  "What gestures do teachers use most?",
  "Give three examples of positive body language.",
  "What are some “bad” gestures?",
  "How do young and old people use body language or gestures differently?",
  "What is a ,body language expert,?",
  "Would you be good at this job?",
  "What body language have you used today?",
  "What is a greeting? Give three examples.",
  "What’s the difference between body language, a gesture, and a greeting?",
  "What are some popular gestures in your country?",
  "Who invents gestures? How do they begin?",
  "Give three examples of how gestures can be used while traveling?",
  "What gestures do you use most often?",
  "Give three examples of negative body language.",
  "What are three American gestures?",
  "What gestures do athletes use most?",
  "What is a ‘brand’?",
  "What is a popular brand for young people?",
  "What are two brands that you don’t like?",
  "What is your favorite snack brand?",
  "What is the most famous brand in the world? Do you like it?",
  "What brand has the coolest logo? Why do you think so?",
  "Why do people like brand name clothing?",
  "If you could create your own brand name product, what would it be? Why?",
  "Is brand name important to you? Why or why not?",
  "What is the most popular brand in your country?",
  "What is a popular brand for older people?",
  "What are two brands that you like?",
  "What is your favorite drink brand?",
  "What’s your family’s favorite brand?",
  "What brand has a popular slogan? What is it? Why is it popular?",
  "There are two identical products in front of you, one brand-less and one your favorite brand.",
  "Would you pay $10 more for your favorite brand? Why or why not?",
  "What’s the best technology brand? Why?",
  "What brand will still be popular in 20 years? 50 years? Why?",
  "What is a challenge?",
  "What are some challenges for elderly people?",
  "What is the most challenging part of your day?",
  "Which is more challenging, math or English?",
  "Are challenging situations good or bad?",
  "Talk about a challenge you had in elementary school.",
  "Describe a challenge you had in middle school.",
  "What challenges do men face?",
  "What is the most challenging job at a school?",
  "What challenge has your country overcome?",
  "Describe a challenge you had in middle school.",
  "Which job is the most challenging?",
  "What are some challenges for people in their 20’s?",
  "What is your mood when you face a challenging situation?",
  "What is the least challenging subject at school?",
  "What are some challenges for restaurant owners?",
  "What challenges do women face?",
  "When you are older, would you like to have a challenging job or an unchallenging one?",
  "What challenges will you face as you grow older?",
  "Have you ever failed a challenge? Explain.",
  "Is it better to be rich and ugly or poor and beautiful?",
  "Which is tastier, chocolate cookies or strawberry ice cream?",
  "Which is more entertaining, playing smart phone games or playing board games?",
  "Which is prettier, sunrise or sunset?",
  "Do you think water or juice is more refreshing?",
  "Who is a better cook, you or your mom or grandma?",
  "Do you think reading or writing is more interesting?",
  "Which is more delicious, restaurant food or your mom’s cooking?",
  "Which makes a better pet, a dog or a rabbit?",
  "Which job is more difficult, a teacher or a chef?",
  "Which is better for your health, a good diet or regular exercise?",
  "Do you think English or Chinese is harder?",
  "Is it better to live in a small house or a big apartment?",
  "Which is more enjoyable, going to a funny movie or a delicious restaurant?",
  "Which sport is more fun, soccer or badminton?",
  "Who is smarter, you or your brother/sister?",
  "Which is more fun, action movies or animated movies?",
  "Do you think December or January is colder?",
  "Which is better, getting 100% on a test or getting $50 for your birthday?",
  "Who is funnier, Mom or Dad?",
  "Describe a typical dish from your country. What are the ingredients? When do you eat it?",
  "What is a popular vacation destination for people in your country? Have you been there before?",
  "Talk about a person who is a role model in your country. What good characteristics does he/she have?",
  "Describe a major holiday in your country. How do you celebrate?",
  "Talk about one inventor from your country. What did he/she invent? Do you use this item today?",
  "If you could change one thing about your country’s culture, what would you change? Why?",
  "Talk about a famous athlete from your country. Why is he/she famous?",
  "What is a highly respected profession in your country? Why?",
  "Talk about a popular singer or band. Describe the act. Who is a fan of this singer/band?",
  "Describe a popular TV show in your country. What is the concept of the show?",
  "Talk about a major historical figure from your country. What did he/she do?",
  "Describe a popular snack in your country.",
  "Talk about your country’s traditional clothing. When do you wear this clothing?",
  "What is the best part of your country’s culture? Why do you think so?",
  "Describe a traditional drink from your country. Do you drink it? Why or why not?",
  "Talk about a famous author or book in your country? Which books have you read?",
  "What’s the worst part of your country’s culture? Why do you think so?",
  "Talk about a big company from your country. What do they make?",
  "What is a popular website in your country? How often do you use it?",
  "What are the three biggest cities in your country? ",
  "What is each city famous for?",
  "How often do you exercise?",
  "What’s your favorite exercise?",
  "What are three easy exercises?",
  "Do you think people should exercise every day?",
  "Do your parents exercise often?",
  "What is a popular exercise for young people? Old people?",
  "When is the best time of day to exercise?",
  "Do you prefer swimming or bike riding?",
  "What does this quote mean?: ‘It is health that is real wealth not pieces of gold and silver.’ -Ghandi",
  "How many hours a week do you exercise?",
  "What’s your least favorite exercise?",
  "What are three difficult exercises?",
  "When did you last exercise?",
  "Why is exercise important?",
  "What is a good amount of time to exercise?",
  "Do prefer exercising indoors or outdoors?",
  "Do you prefer jogging or hiking?",
  "What does this quote mean?: ‘To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear.’ -Buddha",
  "Have you (or someone you know) ever been in a car accident?",
  "Describe the happiest moment of your life.",
  "Have you ever performed in front of an audience?",
  "Have you ever experienced homesickness?",
  "Describe a terrible food you have eaten.",
  "Describe an embarrassing moment you had.",
  "Have you ever been injured playing a game?",
  "Describe a time in your childhood when you were really excited about something.",
  "Have you ever won a prize, contest, or lottery?",
  "Describe the most fun vacation you have ever taken.",
  "Have you ever met a celebrity?",
  "Have you ever been in the hospital for more than a week?",
  "Have you ever experienced culture shock?",
  "Describe a time when you were really angry.",
  "What is the hardest challenge you’ve ever attempted?",
  "What is the proudest moment of your life?",
  "Describe a time when you failed at something.",
  "Describe a time when your parents were really happy at something you did.",
  "Have you ever been mentioned in the newspaper, radio, TV, or internet?",
  "Describe a time when you felt worried, anxious, or nervous about something.",
  "If you were rich, what would you do?",
  "If you had one wish, what would it be?",
  "If you could be a celebrity for a day, which celebrity would you be?",
  "If you were the principal at school, what would you change?",
  "If you could go anywhere in the world, where would you go and why?",
  "If you were on a deserted island, what would you bring and why?",
  "If you could be any animal for a day, what would it be and why?",
  "If you could have any superpower, what would you pick and why?",
  "If you could pack only 3 items for your next trip, what would they be?",
  "If you could change one thing about yourself, what would it be?",
  "If you could travel to the moon, would you like to go?",
  "If you win the lottery, what is the first thing you would do?",
  "If you owned an island to yourself, what rules would you implement?",
  "If you could pick a Halloween costume to dress up as on Halloween, what would it be?",
  "If you could be born at a different time period, when would it be?",
  "If you could change the past, would you do it?",
  "If you could make a movie, which celebrity would you pick as yourself?",
  "If you found a large amount of money, what would you do?",
  "If you could change anything about your country, what would you change?",
  "If you could be born in another country, which one would you pick?",
  "If you could do your dream job 10 years from now, which job would you choose?",
  "What are you going to have for dinner?",
  "What are your plans for tomorrow?",
  "What are your plans for the weekend?",
  "When is the next time you plan on doing some exercise?",
  "When is the next time you plan on doing some exercise?",
  "What is the next film you would like to see?",
  "What is the next series you would like to watch?",
  "When is the next time you’ll be going to a restaurant?",
  "What would you like to achieve before you’re forty?",
  " What would you like to achieve before you’re fifty?",
  "What would you like to achieve before you die?",
  "Do you want to climb a mountain at some point in your life?",
  "What kind of house do you want to live in when you’re older?",
  "What skills would you like to develop as your get older?",
  "Do you want to have a simple life or an expensive life?",
  "If you could live in any country where would you live?",
  "If you could do any job what would you do?",
  "If you could live in any period of time when would you live?",
  "If you could have any super power what would you have?",
  "If you could meet any famous person who would you want to meet?",
  "If you could be someone else for one day who would you be?",
  "How would you trap a monkey?",
  "How would you get rid of a wasps nest?",
  "How would you make ice cream?",
  "Would you prefer to be a cat or a dog?",
  "Would you prefer to live in a hot country or a cold country?",
  "Would you prefer to live in the mountains or on the beach?",
  "Would you prefer to live in America or in Europe?",
  "Would you prefer to have a dragon or a unicorn?",
  "Would you prefer to visit Mars or the Moon?",
  "Would you prefer to be able to breath under water or to fly?",
  "What would you do with $1,000,000?",
  "Would you prefer to be rich or famous?",
  "If you could live anywhere in the world where would you like to live?",
  "Would you prefer to make a difference in the world or would you prefer to be adored?",
  "Would you rather fight a troll or an ogre?",
  "Would you rather be able to fly or have super strength?",
  "If you could solve one problem in the world what would you like to solve?",
  "What has been the most useful technological advance in the past 100 years?",
  "What has been the biggest technological change in your lifetime?",
  "Which piece of technology do you find most useful in your day to day life?",
  "How will technology help to make our lives easier in the next ten years?",
  "If you had to give up all technology from your life apart from one thing, what would you choose to keep?",
  "What jobs will be lost due to technological advances?",
  "Could technology be causing a rise in obesity? If so how? And how can we combat that?",
  "Do you think young people spend too much time on their phones and in the house compared to earlier generations?",
  "What are some of the disadvantages of computers and the internet?",
  "What did you eat yesterday?",
  "What did you do yesterday?",
  "Where was the last place you went on holiday?",
  "What was the last film you saw?",
  "When was the last time you did exercise?",
  "What is your favorite animal and why?",
  "Are people animals? What separates humans from animals?",
  "Which animal is the most dangerous?",
  "What should you do if a bear approaches you?",
  "Do you like dogs? Why do people call the dog, man's best friend?",
  "Do you enjoy going to the zoo? Some people consider zoos to be cruel environments for animals. What do you think?",
  "Where is the best place to see animals in your country? In the world?",
  "Are you a vegetarian? What makes some people give up eating meat?",
  "Which animal is most helpful to humans?",
  "If you could be any animal (besides human), which animal would you like to be?",
  "Who would win in a fight between a tiger and a lion?",
  "What do you think about hunting animals? Would you like to try it?",
  "Books like Watership Down and Animal Farm give animals human characteristics like human thoughts or language. Is this how you think animals really are? Or are those really just stories about people?",
  "Some animals are endangered due to illegal poaching. How do you feel about this issue?",
  "If we can bring an extinct animal from the past back with genetic engineering, should we do it? Which animals should we bring back?",
  "Have you heard of the law of the jungle? How do you feel about the idea that in nature, animals kill or be killed?",
  "What do you think about the theory of evolution? If animals are still evolving, what will they be like in the future?",
  "What do people mean when they say 'a leopard doesn't change its spots'? Do you agree?",
  "A liger is a cross between a tiger and a lion. What other hybrid animals can you imagine?",
  "Do you think change is important?",
  "Have you made any recent changes in your life ?",
  "Do you ever get the urge to refurnish your whole house?",
  "Do you rearrange the furniture in your house often?",
  "Do you like to rearrange your room or living-room?",
  "Do you think change is important in people's life?",
  "Do you think it is possible for a cold hearted person to change?",
  "Do you think it is easy to keep up with the times?",
  "If you could change anything in your life, what would it be?",
  "What is the most difficult change you have ever had to make?",
  "Have you ever cut your hair really short?",
  "What was the craziest change in appearance you have ever made?",
  "What was the last major change you made in your life?",
  "Have you ever decided to change the group that you usually hang out (spend time) with?",
  "What is one thing that you think you will never change about yourself?",
  "What is one thing you have tried to change, but couldn't?",
  "If you won a million dollars what things would you change about your life?",
  "What things would you keep the same?",
  "Have you ever converted (changed) over to a different religion?",
  "Have you ever changed over to a different political party.",
  "Have you lost a pet, or has a person ever passed away on you?",
  "Have you ever quit your job?",
  "Have you ever decided to change the way you dress? If so, why?",
  "Have you ever decided to change the way you eat, or your form of exercise?",
  "What is one food you've never eaten but would love to try?",
  "What is something great about your country that most people don't know about?",
  "What is the strangest drink or snack flavor you've ever eaten?"
];

export const localIdioms = [
  {
    idiom: "A blessing in disguise",
    meaning: "A good thing that initially seemed bad",
  },

  {
    idiom: "A dime a dozen",
    meaning: "Something that is very common, not unique",
  },

  {
    idiom: "Adding insult to injury",
    meaning: "To make a bad situation even worse",
  },

  {
    idiom: "Beat around the bush",
    meaning:
      "Avoid sharing your true viewpoint or feelings because it is uncomfortable",
  },

  {
    idiom: "Beating a dead horse",
    meaning: "Giving time or energy to something that is ended or over",
  },

  {
    idiom: "Bite the bullet",
    meaning:
      "To get an unfavorable situation or chore over with now because it will need to get finished eventually",
  },

  {
    idiom: "Best of both worlds",
    meaning:
      "The choice or solution has all of the advantages of two contrasting things at the same time",
  },

  {
    idiom: "Biting off more than you can chew",
    meaning:
      "Not having the capacity to take on a new assignment or task that is just too taxing",
  },

  { idiom: "By the skin of your teeth", meaning: "Just barely making it" },

  {
    idiom: "Don’t judge a book by its cover",
    meaning: "Not judging something by its initial appearance",
  },

  {
    idiom: "Doing something at the drop of a hat",
    meaning: "Doing something at the moment of being asked",
  },

  {
    idiom: "Don’t count your chickens before they hatch",
    meaning:
      "Not to count on something happening until after it’s already happened",
  },

  {
    idiom: "Caught between a rock and a hard place",
    meaning: "Making a choice between two unpleasant choices",
  },

  {
    idiom: "Costs an arm and a leg",
    meaning: "Something that is overpriced or very expensive",
  },

  {
    idiom: "Cutting corners",
    meaning:
      "Not performing a task or duty correctly in order to save time or money",
  },

  {
    idiom: "Devil’s advocate",
    meaning:
      "To take the side of the counter-argument, or offer an alternative point of view",
  },

  {
    idiom: "Feeling under the weather",
    meaning: "Not feeling well, or feeling sick",
  },

  { idiom: "Fit as a fiddle", meaning: "Being in good health" },

  {
    idiom: "Getting a taste of your own medicine",
    meaning: "Being treated the way that you have been treating others",
  },

  {
    idiom: "Getting a second wind",
    meaning: "Having energy again after being tired",
  },

  {
    idiom: "Giving the benefit of the doubt",
    meaning:
      "Believing someone’s story without proof even though it may seem unbelievable",
  },

  { idiom: "Giving someone the cold shoulder", meaning: "Ignoring someone" },

  {
    idiom: "Going on a wild goose chase",
    meaning: "Doing something that is pointless",
  },

  {
    idiom: "Heard it through the grapevine",
    meaning: "Hearing rumors about someone or something",
  },

  {
    idiom: "Hitting the nail on the head",
    meaning: "Performing a task with exactness",
  },

  {
    idiom: "Killing two birds with one stone",
    meaning: "Accomplishing two different tasks in the same undertaking",
  },

  {
    idiom: "Letting someone off the hook",
    meaning: "Not holding someone responsible for something",
  },

  {
    idiom: "Letting the cat out of the bag",
    meaning: "Sharing information that was intended to be a secret",
  },

  {
    idiom: "No pain, no gain",
    meaning: "You have to work hard in order to see results",
  },

  {
    idiom: "On the ball",
    meaning: "Doing a good job, being prompt, or being responsible",
  },

  {
    idiom: "Once in a blue moon",
    meaning: "Something that doesn’t happen very often",
  },

  { idiom: "Piece of cake", meaning: "A task or job that is easy to complete" },

  { idiom: "Pulling someone’s leg", meaning: "Joking with someone" },

  {
    idiom: "Speak of the devil",
    meaning: "When the person you have just been talking about arrives",
  },

  {
    idiom: "Stealing someone’s thunder",
    meaning: "Taking credit for someone else’s achievements",
  },

  {
    idiom: "Straight from the horse’s mouth",
    meaning: "Reading or hearing something from the source",
  },

  {
    idiom: "The last straw",
    meaning:
      "The last difficulty or annoyance that makes the entire situation unbearable",
  },

  {
    idiom: "The elephant in the room",
    meaning: "An issue, person, or problem that someone is trying to avoid",
  },

  {
    idiom: "Throwing caution to the wind",
    meaning: "Being reckless or taking a risk",
  },

  { idiom: "Your guess is as good as mine", meaning: "To not know something" },

  {
    idiom: "A snowball effect",
    meaning:
      "Something has momentum and builds on each other, much like rolling a snowball down a hill to make it bigger",
  },

  {
    idiom: "An apple a day keeps the doctor away",
    meaning: "Apples are healthy and good for you",
  },

  {
    idiom: "Burning bridges",
    meaning: "Damaging a relationship beyond repair",
  },

  {
    idiom: "Every dog has his day",
    meaning: "Everyone gets their chance to do something big",
  },

  { idiom: "Fit as a fiddle", meaning: "Excellent health" },

  { idiom: "Go down in flames", meaning: "To fail in a spectacular manner" },

  {
    idiom: "Having your head in the clouds",
    meaning: "Day dreaming, not paying attention",
  },

  {
    idiom: "He/She is off their rocker",
    meaning: "Someone who is acting crazy or not thinking rationally",
  },

  {
    idiom: "It’s always darkest before the dawn",
    meaning: "Things always get worse before they get better",
  },

  {
    idiom: "It takes two to tango",
    meaning: "One person usually isn’t the only responsible party",
  },

  {
    idiom: "Like riding a bike",
    meaning: "Something that you never forget how to do",
  },

  {
    idiom: "Like two peas in a pod",
    meaning: "Two people who are always together",
  },

  { idiom: "like the wind", meaning: "To run really fast" },

  {
    idiom: "Through thick and thin",
    meaning: "Everyone experiences hard and good times",
  },

  { idiom: "Time is money", meaning: "Work faster or more efficiently" },

  { idiom: "Weather the storm", meaning: "Enduring a trial or hardship" },

  {
    idiom: "Can’t make an omelet without breaking some eggs",
    meaning: "You can’t make everyone happy",
  },

  {
    idiom: "You can lead a horse to water, but you can’t make him drink",
    meaning:
      "You can’t force someone to make what is seemingly the right decision",
  },

  {
    idiom: "Clouds on the horizon",
    meaning: "Trouble is coming or is on its way",
  },

  {
    idiom: "Hit the hay.",
    meaning: "To go to bed",
  },
  {
    idiom: "Up in the air.",
    meaning: "Not decided yet.",
  },

  {
    idiom: "Piece of cake.",
    Meaning: "Very easy",
  },
  {
    idiom: "Costs an arm and a leg.",
    meaning: "Very expensive.",
  },
  {
    idiom: "Break a leg",
    meaning: "Good luck",
  },
  {
    idiom: "Rule of thumb",
    meaning: "A rule based off of common experience and common sense.",
  },
  {
    idiom: "Blow of steam.",
    meaning: "Doing an activity to release stress",
  },
];
